// Auto-generated by Luban Editor
using System;

namespace Puffin.Modules.ConfigModule.Runtime
{
    public static class ConfigLoader
    {
        public static Type TablesType => typeof(PuffinFrameworks.Config.Gen.Tables);

        public static object CreateTables(Func<string, byte[]> loader) => new PuffinFrameworks.Config.Gen.Tables(name => new Luban.ByteBuf(loader(name)));
    }
}
