
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace PuffinFrameworks.Config.Gen.demo
{
public partial class Tbitem
{
    private readonly System.Collections.Generic.Dictionary<int, demo.item> _dataMap;
    private readonly System.Collections.Generic.List<demo.item> _dataList;
    
    public Tbitem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.item>(n);
        _dataList = new System.Collections.Generic.List<demo.item>(n);
        for(int i = n ; i > 0 ; --i)
        {
            demo.item _v;
            _v = global::PuffinFrameworks.Config.Gen.demo.item.Deserializeitem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.item> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.item> DataList => _dataList;

    public demo.item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.item Get(int key) => _dataMap[key];
    public demo.item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

