# GitHub Actions workflow for auto-updating registry.json
# 放置在 .github/workflows/ 目录下

name: Update Registry

on:
  push:
    paths:
      - 'modules/**/manifest.json'
  workflow_dispatch:

jobs:
  update-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate registry.json
        run: python scripts/generate_registry.py

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add registry.json
          git diff --staged --quiet || git commit -m "Auto-update registry.json"
          git push
